export const RESPONSIVE_CARD_GRID_CLASSES = 'jl-responsive-card-grid';

export const PRODUCT_GRID_CLASSES = RESPONSIVE_CARD_GRID_CLASSES;
export const CATEGORY_GRID_CLASSES = RESPONSIVE_CARD_GRID_CLASSES;
export const SERVICE_GRID_CLASSES = RESPONSIVE_CARD_GRID_CLASSES;
export const BRIDAL_GRID_CLASSES = RESPONSIVE_CARD_GRID_CLASSES;

export const GALLERY_GRID_CLASSES = 'jl-responsive-gallery-grid';
