export type Product = {
  id: string;
  name: string;
  price: number;
  oldPrice?: number;
  category?: string;
  type: 'product' | 'service';
  description?: string;
  image: string;
  gallery?: string[];
  sku?: string;
  rating?: number;
  reviewCount?: number;
  discount?: number;
  isNew?: boolean;
  featured?: boolean;
  bestseller?: boolean;
  stock?: number;
  sizes?: string[];
  active?: boolean;
};
export type Category={id:string;name:string;slug?:string;type:'product'|'service';description?:string;image?:string;active?:boolean;createdAt?:string;};
export type Order={
	id:string;
	userId?:string;
	accessToken?:string;
	customerEmailLower?:string;
	paymentStatus?:string;
	items:{id?:string;name?:string;category?:string;price?:number;qty?:number;quantity?:number;image?:string}[];
	subtotal:number;
	shipping:number;
	tax:number;
	total:number;
	taxRate?:number;
	shippingFee?:number;
	discountAmount?:number;
	paymentMethod:string;
	paymentReference?:string;
	status:string;
	createdAt:string;
	customer?:{name:string;phone:string;address:string};
	customerEmail?:string;
	customerName?:string;
	customerPhone?:string;
	customerAddress?:string;
	shippingAddress?:string;
	address?:string;
	deliveryDays?: string;
    deliveryDaysCount?: number;
    estimatedDeliveryDate?: string;
    courier?: string;
    trackingNumber?: string;
    trackingUrl?: string;
    deliveredAt?: string;
    cancelledAt?: string;
    refundedAt?: string;
    updatedAt?: string;
    confirmationEmailStatus?: string;
    confirmationEmailId?: string | null;
    confirmationEmailError?: string | null;
    confirmationEmailSentAt?: string | null;
    paymentEmailStatus?: string;
    paymentEmailId?: string | null;
    paymentEmailError?: string | null;
    paymentEmailSentAt?: string | null;
    statusEmailLastStatus?: string;
    statusEmailStatus?: string;
    statusEmailId?: string | null;
    statusEmailError?: string | null;
    statusEmailSentAt?: string | null;
    lastEmailType?: string;
    lastEmailStatus?: string;
    lastEmailSentAt?: string | null;
    lastEmailDeliveryStatus?: string;
    lastEmailProviderEvent?: string;
    lastEmailProviderEventAt?: string | null;
};
export type Session={id:string;userId:string;email:string;loginAt:string;userAgent:string};
export type BridalPackage = {
  id: string;
  name: string;
  title?: string;
  description: string;
  image: string;
  price: number;
  features: string[];
  duration?: string;
  active?: boolean;
  featured: boolean;
  popular?: boolean;
  createdAt?: string;
};
export type Transformation = {
  id: string;
  title: string;
  category: string;
  beforeImage: string;
  afterImage: string;
  description: string;
  featured: boolean;
  createdAt?: string;
};